PCG-13620 | Change the Alert Type of Serverless Protection
sophos/Sophos-Cloud-Optix-Remediation-Functions pull request #7
Opened 2023-04-28 10:14 UTC by rajlaxmiSophos

2023-05-01 05:51 UTC, prasoon124 approved these changes

2023-05-01 05:59 UTC, prasoon421 approved these changes

2023-05-02 13:48 UTC, prasoon124 approved these changes

2023-05-02 14:54 UTC, prasoon421 approved these changes

2023-05-03 08:31 UTC, ghost approved these changes

2023-05-03 10:29 UTC, prasoon421 requested changes
This is an old file which was present when we had the alert type S3 malware

2023-08-26 07:18 UTC, closed without merging